sudo: required
services:
    - docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true USERNAME/react-test npm test

after_success:
    - docker build -t influenceandrew/multi-client ./client
    - docker build -t influenceandrew/multi-nginx ./nginx
    - docker build -t influenceandrew/multi-server ./server
    - docker build -t influenceandrew/multi-worker ./worker

